meta_title: "Terms of Service; Didn't Read - Phoenix"
meta_description: "I have read and understood the terms of service is the biggest lie on the Internet. We aim to fix that."
meta_image: "logo.png"
twitter_account: "@tosdr"
